# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20160423_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='places.Place'),
        ),
    ]
