# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-24 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20160423_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='extra_data',
            field=models.TextField(blank=True),
        ),
    ]
