# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-24 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_feedback_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
    ]
