# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-24 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
